services:
  app:
    build:
      context: ./backend
      dockerfile: docker/dockerfiles/laravel/Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    ports:
      - 9000:9000
    networks:
      - laravel
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - docker/env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  frontend:
    build:
      context: ./frontend/app
      dockerfile: ../../docker/dockerfiles/vue/Dockerfile
    container_name: vue-app
    volumes:
      - ./frontend/app:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - laravel

#  php:
#    build:
#      context: docker/dockerfiles
#      dockerfile: php/Dockerfile
#    volumes:
#      - ./src:/var/www/laravel

#  composer:
#    build:
#      context: docker
#      dockerfile: dockerfiles/composer/Dockerfile
#    volumes:
#      - ./backend:/var/www

#  artisan:
#    build:
#      context: dockerfiles
#      dockerfile: composer/Dockerfile
#    volumes:
#      - ./src:/var/www/laravel
#    entrypoint: ["Dockerfile", "/var/www/laravel/artisan"]
#


networks:
  laravel:

volumes:
  db_data: